// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOEKkHZTS-KeuuIBUOz6Vqye8trX4twY',
    appId: '1:371102131768:web:c75d3aae4460f926c8e8cd',
    messagingSenderId: '371102131768',
    projectId: 'bookbee-7a153',
    authDomain: 'bookbee-7a153.firebaseapp.com',
    storageBucket: 'bookbee-7a153.firebasestorage.app',
    measurementId: 'G-DLMW4DBS12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDU9VftAguc2QzGlc1RzadnJ1MVbNfeTo',
    appId: '1:371102131768:android:6b8d3d39fa9262a8c8e8cd',
    messagingSenderId: '371102131768',
    projectId: 'bookbee-7a153',
    storageBucket: 'bookbee-7a153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlSerkienLwwKaRS8aM_4TMUhhh9n_V2Q',
    appId: '1:371102131768:ios:8c6c6e7c50d75151c8e8cd',
    messagingSenderId: '371102131768',
    projectId: 'bookbee-7a153',
    storageBucket: 'bookbee-7a153.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookbee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlSerkienLwwKaRS8aM_4TMUhhh9n_V2Q',
    appId: '1:371102131768:ios:8c6c6e7c50d75151c8e8cd',
    messagingSenderId: '371102131768',
    projectId: 'bookbee-7a153',
    storageBucket: 'bookbee-7a153.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookbee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGOEKkHZTS-KeuuIBUOz6Vqye8trX4twY',
    appId: '1:371102131768:web:3b7b416bd64886e7c8e8cd',
    messagingSenderId: '371102131768',
    projectId: 'bookbee-7a153',
    authDomain: 'bookbee-7a153.firebaseapp.com',
    storageBucket: 'bookbee-7a153.firebasestorage.app',
    measurementId: 'G-7ZBDG4LKZ5',
  );
}
